// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: protos/stream.proto

package streamdl

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StreamInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Site           string                 `protobuf:"bytes,1,opt,name=site,proto3" json:"site,omitempty"`
	User           string                 `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	Quality        string                 `protobuf:"bytes,3,opt,name=quality,proto3" json:"quality,omitempty"`
	OutputTemplate string                 `protobuf:"bytes,4,opt,name=output_template,json=outputTemplate,proto3" json:"output_template,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *StreamInfo) Reset() {
	*x = StreamInfo{}
	mi := &file_protos_stream_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamInfo) ProtoMessage() {}

func (x *StreamInfo) ProtoReflect() protoreflect.Message {
	mi := &file_protos_stream_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamInfo.ProtoReflect.Descriptor instead.
func (*StreamInfo) Descriptor() ([]byte, []int) {
	return file_protos_stream_proto_rawDescGZIP(), []int{0}
}

func (x *StreamInfo) GetSite() string {
	if x != nil {
		return x.Site
	}
	return ""
}

func (x *StreamInfo) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *StreamInfo) GetQuality() string {
	if x != nil {
		return x.Quality
	}
	return ""
}

func (x *StreamInfo) GetOutputTemplate() string {
	if x != nil {
		return x.OutputTemplate
	}
	return ""
}

type StreamResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Error         int32                  `protobuf:"varint,2,opt,name=error,proto3" json:"error,omitempty"`
	AudioUrl      string                 `protobuf:"bytes,3,opt,name=audio_url,json=audioUrl,proto3" json:"audio_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamResponse) Reset() {
	*x = StreamResponse{}
	mi := &file_protos_stream_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamResponse) ProtoMessage() {}

func (x *StreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_stream_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamResponse.ProtoReflect.Descriptor instead.
func (*StreamResponse) Descriptor() ([]byte, []int) {
	return file_protos_stream_proto_rawDescGZIP(), []int{1}
}

func (x *StreamResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *StreamResponse) GetError() int32 {
	if x != nil {
		return x.Error
	}
	return 0
}

func (x *StreamResponse) GetAudioUrl() string {
	if x != nil {
		return x.AudioUrl
	}
	return ""
}

type VodRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Site          string                 `protobuf:"bytes,1,opt,name=site,proto3" json:"site,omitempty"`
	User          string                 `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VodRequest) Reset() {
	*x = VodRequest{}
	mi := &file_protos_stream_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VodRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VodRequest) ProtoMessage() {}

func (x *VodRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_stream_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VodRequest.ProtoReflect.Descriptor instead.
func (*VodRequest) Descriptor() ([]byte, []int) {
	return file_protos_stream_proto_rawDescGZIP(), []int{2}
}

func (x *VodRequest) GetSite() string {
	if x != nil {
		return x.Site
	}
	return ""
}

func (x *VodRequest) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *VodRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type VodInfo struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title           string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	PublishedAt     string                 `protobuf:"bytes,3,opt,name=published_at,json=publishedAt,proto3" json:"published_at,omitempty"`
	DurationSeconds int64                  `protobuf:"varint,4,opt,name=duration_seconds,json=durationSeconds,proto3" json:"duration_seconds,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *VodInfo) Reset() {
	*x = VodInfo{}
	mi := &file_protos_stream_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VodInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VodInfo) ProtoMessage() {}

func (x *VodInfo) ProtoReflect() protoreflect.Message {
	mi := &file_protos_stream_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VodInfo.ProtoReflect.Descriptor instead.
func (*VodInfo) Descriptor() ([]byte, []int) {
	return file_protos_stream_proto_rawDescGZIP(), []int{3}
}

func (x *VodInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *VodInfo) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *VodInfo) GetPublishedAt() string {
	if x != nil {
		return x.PublishedAt
	}
	return ""
}

func (x *VodInfo) GetDurationSeconds() int64 {
	if x != nil {
		return x.DurationSeconds
	}
	return 0
}

type VodResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vods          []*VodInfo             `protobuf:"bytes,1,rep,name=vods,proto3" json:"vods,omitempty"`
	Error         int32                  `protobuf:"varint,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VodResponse) Reset() {
	*x = VodResponse{}
	mi := &file_protos_stream_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VodResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VodResponse) ProtoMessage() {}

func (x *VodResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_stream_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VodResponse.ProtoReflect.Descriptor instead.
func (*VodResponse) Descriptor() ([]byte, []int) {
	return file_protos_stream_proto_rawDescGZIP(), []int{4}
}

func (x *VodResponse) GetVods() []*VodInfo {
	if x != nil {
		return x.Vods
	}
	return nil
}

func (x *VodResponse) GetError() int32 {
	if x != nil {
		return x.Error
	}
	return 0
}

var File_protos_stream_proto protoreflect.FileDescriptor

const file_protos_stream_proto_rawDesc = "" +
	"\n" +
	"\x13protos/stream.proto\x12\x06protos\"w\n" +
	"\n" +
	"StreamInfo\x12\x12\n" +
	"\x04site\x18\x01 \x01(\tR\x04site\x12\x12\n" +
	"\x04user\x18\x02 \x01(\tR\x04user\x12\x18\n" +
	"\aquality\x18\x03 \x01(\tR\aquality\x12'\n" +
	"\x0foutput_template\x18\x04 \x01(\tR\x0eoutputTemplate\"U\n" +
	"\x0eStreamResponse\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x14\n" +
	"\x05error\x18\x02 \x01(\x05R\x05error\x12\x1b\n" +
	"\taudio_url\x18\x03 \x01(\tR\baudioUrl\"J\n" +
	"\n" +
	"VodRequest\x12\x12\n" +
	"\x04site\x18\x01 \x01(\tR\x04site\x12\x12\n" +
	"\x04user\x18\x02 \x01(\tR\x04user\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\"}\n" +
	"\aVodInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12!\n" +
	"\fpublished_at\x18\x03 \x01(\tR\vpublishedAt\x12)\n" +
	"\x10duration_seconds\x18\x04 \x01(\x03R\x0fdurationSeconds\"H\n" +
	"\vVodResponse\x12#\n" +
	"\x04vods\x18\x01 \x03(\v2\x0f.protos.VodInfoR\x04vods\x12\x14\n" +
	"\x05error\x18\x02 \x01(\x05R\x05error2u\n" +
	"\x06Stream\x127\n" +
	"\tGetStream\x12\x12.protos.StreamInfo\x1a\x16.protos.StreamResponse\x122\n" +
	"\aGetVods\x12\x12.protos.VodRequest\x1a\x13.protos.VodResponseB\"Z dangerous.tech/streamdl;streamdlb\x06proto3"

var (
	file_protos_stream_proto_rawDescOnce sync.Once
	file_protos_stream_proto_rawDescData []byte
)

func file_protos_stream_proto_rawDescGZIP() []byte {
	file_protos_stream_proto_rawDescOnce.Do(func() {
		file_protos_stream_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protos_stream_proto_rawDesc), len(file_protos_stream_proto_rawDesc)))
	})
	return file_protos_stream_proto_rawDescData
}

var file_protos_stream_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_protos_stream_proto_goTypes = []any{
	(*StreamInfo)(nil),     // 0: protos.StreamInfo
	(*StreamResponse)(nil), // 1: protos.StreamResponse
	(*VodRequest)(nil),     // 2: protos.VodRequest
	(*VodInfo)(nil),        // 3: protos.VodInfo
	(*VodResponse)(nil),    // 4: protos.VodResponse
}
var file_protos_stream_proto_depIdxs = []int32{
	3, // 0: protos.VodResponse.vods:type_name -> protos.VodInfo
	0, // 1: protos.Stream.GetStream:input_type -> protos.StreamInfo
	2, // 2: protos.Stream.GetVods:input_type -> protos.VodRequest
	1, // 3: protos.Stream.GetStream:output_type -> protos.StreamResponse
	4, // 4: protos.Stream.GetVods:output_type -> protos.VodResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_protos_stream_proto_init() }
func file_protos_stream_proto_init() {
	if File_protos_stream_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protos_stream_proto_rawDesc), len(file_protos_stream_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_stream_proto_goTypes,
		DependencyIndexes: file_protos_stream_proto_depIdxs,
		MessageInfos:      file_protos_stream_proto_msgTypes,
	}.Build()
	File_protos_stream_proto = out.File
	file_protos_stream_proto_goTypes = nil
	file_protos_stream_proto_depIdxs = nil
}
