# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protos/stream.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'protos/stream.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13protos/stream.proto\x12\x06protos\"R\n\nStreamInfo\x12\x0c\n\x04site\x18\x01 \x01(\t\x12\x0c\n\x04user\x18\x02 \x01(\t\x12\x0f\n\x07quality\x18\x03 \x01(\t\x12\x17\n\x0foutput_template\x18\x04 \x01(\t\"?\n\x0eStreamResponse\x12\x0b\n\x03url\x18\x01 \x01(\t\x12\r\n\x05\x65rror\x18\x02 \x01(\x05\x12\x11\n\taudio_url\x18\x03 \x01(\t\"7\n\nVodRequest\x12\x0c\n\x04site\x18\x01 \x01(\t\x12\x0c\n\x04user\x18\x02 \x01(\t\x12\r\n\x05limit\x18\x03 \x01(\x05\"T\n\x07VodInfo\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x14\n\x0cpublished_at\x18\x03 \x01(\t\x12\x18\n\x10\x64uration_seconds\x18\x04 \x01(\x03\";\n\x0bVodResponse\x12\x1d\n\x04vods\x18\x01 \x03(\x0b\x32\x0f.protos.VodInfo\x12\r\n\x05\x65rror\x18\x02 \x01(\x05\x32u\n\x06Stream\x12\x37\n\tGetStream\x12\x12.protos.StreamInfo\x1a\x16.protos.StreamResponse\x12\x32\n\x07GetVods\x12\x12.protos.VodRequest\x1a\x13.protos.VodResponseB\"Z dangerous.tech/streamdl;streamdlb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.stream_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z dangerous.tech/streamdl;streamdl'
  _globals['_STREAMINFO']._serialized_start=31
  _globals['_STREAMINFO']._serialized_end=113
  _globals['_STREAMRESPONSE']._serialized_start=115
  _globals['_STREAMRESPONSE']._serialized_end=178
  _globals['_VODREQUEST']._serialized_start=180
  _globals['_VODREQUEST']._serialized_end=235
  _globals['_VODINFO']._serialized_start=237
  _globals['_VODINFO']._serialized_end=321
  _globals['_VODRESPONSE']._serialized_start=323
  _globals['_VODRESPONSE']._serialized_end=382
  _globals['_STREAM']._serialized_start=384
  _globals['_STREAM']._serialized_end=501
# @@protoc_insertion_point(module_scope)
