// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protos/stream.proto

package streamdl

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type StreamInfo struct {
	Site                 string   `protobuf:"bytes,1,opt,name=site,proto3" json:"site,omitempty"`
	User                 string   `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	Quality              string   `protobuf:"bytes,3,opt,name=quality,proto3" json:"quality,omitempty"`
	OutputTemplate       string   `protobuf:"bytes,4,opt,name=output_template,json=outputTemplate,proto3" json:"output_template,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StreamInfo) Reset()         { *m = StreamInfo{} }
func (m *StreamInfo) String() string { return proto.CompactTextString(m) }
func (*StreamInfo) ProtoMessage()    {}
func (*StreamInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_bbe9a4fd165e7f68, []int{0}
}

func (m *StreamInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StreamInfo.Unmarshal(m, b)
}
func (m *StreamInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StreamInfo.Marshal(b, m, deterministic)
}
func (m *StreamInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StreamInfo.Merge(m, src)
}
func (m *StreamInfo) XXX_Size() int {
	return xxx_messageInfo_StreamInfo.Size(m)
}
func (m *StreamInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_StreamInfo.DiscardUnknown(m)
}

var xxx_messageInfo_StreamInfo proto.InternalMessageInfo

func (m *StreamInfo) GetSite() string {
	if m != nil {
		return m.Site
	}
	return ""
}

func (m *StreamInfo) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

func (m *StreamInfo) GetQuality() string {
	if m != nil {
		return m.Quality
	}
	return ""
}

func (m *StreamInfo) GetOutputTemplate() string {
	if m != nil {
		return m.OutputTemplate
	}
	return ""
}

type StreamResponse struct {
	Url                  string   `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Error                int32    `protobuf:"varint,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StreamResponse) Reset()         { *m = StreamResponse{} }
func (m *StreamResponse) String() string { return proto.CompactTextString(m) }
func (*StreamResponse) ProtoMessage()    {}
func (*StreamResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_bbe9a4fd165e7f68, []int{1}
}

func (m *StreamResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StreamResponse.Unmarshal(m, b)
}
func (m *StreamResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StreamResponse.Marshal(b, m, deterministic)
}
func (m *StreamResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StreamResponse.Merge(m, src)
}
func (m *StreamResponse) XXX_Size() int {
	return xxx_messageInfo_StreamResponse.Size(m)
}
func (m *StreamResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StreamResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StreamResponse proto.InternalMessageInfo

func (m *StreamResponse) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *StreamResponse) GetError() int32 {
	if m != nil {
		return m.Error
	}
	return 0
}

func init() {
	proto.RegisterType((*StreamInfo)(nil), "protos.StreamInfo")
	proto.RegisterType((*StreamResponse)(nil), "protos.StreamResponse")
}

func init() { proto.RegisterFile("protos/stream.proto", fileDescriptor_bbe9a4fd165e7f68) }

var fileDescriptor_bbe9a4fd165e7f68 = []byte{
	// 220 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x90, 0xbf, 0x4b, 0x04, 0x31,
	0x10, 0x85, 0x39, 0xef, 0x87, 0xdc, 0x14, 0xa7, 0x8c, 0x22, 0xc1, 0xea, 0xd8, 0x46, 0xab, 0x15,
	0xb4, 0x50, 0xb0, 0xd2, 0x46, 0x6c, 0x57, 0x2b, 0x1b, 0x89, 0xee, 0xa8, 0x0b, 0xd9, 0x4d, 0xcc,
	0x4c, 0x10, 0xff, 0x7b, 0xd9, 0x4c, 0x16, 0xb9, 0xee, 0xbd, 0x8f, 0x84, 0x8f, 0x79, 0x70, 0x14,
	0xa2, 0x17, 0xcf, 0x17, 0x2c, 0x91, 0x6c, 0x5f, 0xe7, 0x86, 0x2b, 0x85, 0xd5, 0x0f, 0xc0, 0x53,
	0xe6, 0x8f, 0xc3, 0x87, 0x47, 0x84, 0x05, 0x77, 0x42, 0x66, 0xb6, 0x9d, 0x9d, 0xaf, 0x9b, 0x9c,
	0x47, 0x96, 0x98, 0xa2, 0xd9, 0x53, 0x36, 0x66, 0x34, 0xb0, 0xff, 0x9d, 0xac, 0xeb, 0xe4, 0xd7,
	0xcc, 0x33, 0x9e, 0x2a, 0x9e, 0xc1, 0x81, 0x4f, 0x12, 0x92, 0xbc, 0x0a, 0xf5, 0xc1, 0x59, 0x21,
	0xb3, 0xc8, 0x2f, 0x36, 0x8a, 0x9f, 0x0b, 0xad, 0x6e, 0x60, 0xa3, 0xe2, 0x86, 0x38, 0xf8, 0x81,
	0x09, 0x0f, 0x61, 0x9e, 0xa2, 0x2b, 0xee, 0x31, 0xe2, 0x31, 0x2c, 0x29, 0x46, 0xaf, 0xee, 0x65,
	0xa3, 0xe5, 0xf2, 0x0e, 0x56, 0xfa, 0x13, 0xaf, 0x61, 0xfd, 0x40, 0x52, 0x0a, 0xea, 0x65, 0x5c,
	0xff, 0xdf, 0x73, 0x7a, 0xb2, 0xcb, 0x26, 0xd5, 0x7d, 0xf5, 0xb2, 0x6d, 0xed, 0xf0, 0x49, 0xd1,
	0x27, 0xae, 0x85, 0xde, 0xbf, 0xca, 0x38, 0xad, 0xbb, 0x9d, 0xc2, 0x9b, 0x2e, 0x74, 0xf5, 0x17,
	0x00, 0x00, 0xff, 0xff, 0x38, 0x24, 0xac, 0x85, 0x3f, 0x01, 0x00, 0x00,
}
